### ISSUE TITLE
Change components to LIT

### ISSUE THREAD

**Issue by elYanuki** [htl-leo-itp-2325-4-5BHITM/cam-connect#34]

**Comment by elYanuki** [comment]
dont know if these will actually be visible via editor tooltips, but for checking whats possible we need a jsdoc for these

**Comment by Michiii11** [comment]
there are a few things still todo:
- Confirmationstatus name
- X Icon
- Onclick on select component

**Comment by elYanuki** [comment]
looks fine:
the select component should either be done with slots or like the filter container
