### ISSUE TITLE
Implement component changes

### ISSUE THREAD

**Issue by elYanuki** [htl-leo-itp-2325-4-5BHITM/cam-connect#48]
VerificationStatus
- should be renamed to rentStatus
- add "returned" option (like in figma)
- change padding 
- change font size

PropertyValue
- add isLink option

Button
- changed accent background color
- added "Text" varient
- added x-small size

Filters
- added Nesting

**Comment by Michiii11** [comment]
don't really understand the filter thing rn

**Comment by elYanuki** [comment]
looks good

will implement Nesting later
