### ISSUE TITLE
Create Websockets

### ISSUE THREAD

**Issue by elYanuki** [htl-leo-itp-2325-4-5BHITM/cam-connect#51]
The getAll functions for Rents and Devices should automatically be refreshed by a socket connection when updated by a different client

**Comment by Stevan06v** [comment]
nice ay ay captain

**Comment by Stevan06v** [comment]
back to black

**Comment by elYanuki** [comment]
is now working

**Comment by elYanuki** [comment]
we rewrote these to just send a string "update" that tells the client to query the data from the server again, this allows the clients to store custom filters and request only the needed data.
