### ISSUE TITLE
disable editing of confirmed rents

### ISSUE THREAD

**Issue by elYanuki** [htl-leo-itp-2325-4-5BHITM/cam-connect#55]

**Comment by elYanuki** [comment]
when the confirmation status of a rent is confirmed all inputs except for the return date should be [disabled](https://www.w3schools.com/tags/att_input_disabled.asp)

**Comment by Michiii11** [comment]
changed it that if it's waiting i it is disabled as well

**Comment by elYanuki** [comment]
added "not allowed" cursor and made note always editable

**Comment by elYanuki** [comment]
updating the return- date, teacher or note on a confirmed rent still does not work
