### ISSUE TITLE
Implement static rent list

### ISSUE THREAD

**Issue by elYanuki** [htl-leo-itp-2325-4-5BHITM/cam-connect#62]
rents should be displayed in the frontend as they are queried from the db: no edit functionality is required for now

**Comment by elYanuki** [comment]
welp.. took a look at this code today, there is a lot that has to change here:
- as mentioned all the font sizes should be adjusted to small to make everything less cramed or at least not "big"
- please take a look at the function names section in the code convetions
    - functions like `getButtonAsTextOfStatus` are really hard to understand what the are doing, a better name would be `rentStatusToButtonText` 
- please take a look at the css specific section in the conventions especially the last two points are relevant
- passing the rent to the rentList as a id and then querying it again from the model is a horrible workarround to the type safety and i honestly dont understand why you would even do it this way
    - please pass the rent object to the rent-list-entry inside the map function, you might need to use `.propertyName` instead of `propertyName` to be able to pass complex types and not just simple strings/numbers to the component
    - please get rid of the generateStudent function in rentList
- please use a propertyValue component to display the teacher instead of recreating it from scratch
- please dont use lables for things that are not labeling something: for simple dashes( - ) a span is the better choice. For the vertical line id prefer using the existing line component since that will also take the height propperly and is generally a nicer solution
- it would be smart to put the student-rent-entry into its own component that stores its own id and styles itself and then has the edit functions
- the implementation of the selection behaviour makes no sense: in order to be able to build onto this and add actual functionality you need to keep track of the selected items in a list.. probably only need to store the element reference
- the selection circles should all be position in line, the mutliple select should be some 20% or so bigger so that the actual circle is the same size as the single select

still very good work lol u kinda rescued the sprint review cause aberger doesnt value work but just wants to see quick results <3

**Comment by Michiii11** [comment]
<3
