### ISSUE TITLE
Change Student import to Sokrates standard

### ISSUE THREAD

**Issue by Michiii11** [htl-leo-itp-2325-4-5BHITM/cam-connect#63]
the device input box should have a popup that allows to search and select the devices

for now this should simply work via devices and ignore devicetypes

**Comment by elYanuki** [comment]
@Michiii11 does this actually have high priority? do we want to move forwards with the old web version? what did aberger tell you in that regard?

**Comment by elYanuki** [comment]
I cleaned up the verification a little, seems fine now
