### ISSUE TITLE
Make rent list functional

### ISSUE THREAD

**Issue by Michiii11** [htl-leo-itp-2325-4-5BHITM/cam-connect#81]
there should be the option to delete, return or edit rents

**Comment by elYanuki** [comment]
the edit functionality itself looks fine.

Please prevent students that have no active rents assigned to them from being rendered

I assume you already tested this thoroughly in all different orders with more data etc.

**Comment by elYanuki** [comment]
students with not active rents no longer render

**Comment by elYanuki** [comment]
since this is such an essential part of the codebase and will be worked on a lot in the future, please take the time to clean up your code: i have left comments

**Comment by elYanuki** [comment]
Bugs
- [ ] date updating
- [ ] deleting while chip open
